version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: db_hp
      POSTGRES_USER: yngcrovi
      POSTGRES_PASSWORD: qwerfdsa
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"