version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres_health_page
    env_file:
      - ./.env
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis_health_page
    ports:
      - "6379:6379"
    
volumes:
  redis-data: